# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7cd665b062fccc04cbbbe85d60436421"
name = "mandolly-tech-anjan"
handle = "mandolly-tech-anjan"
application_url = "https://acc-skins-realty-highways.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "mandolly-tech-anjan.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://acc-skins-realty-highways.trycloudflare.com/auth/callback",
  "https://acc-skins-realty-highways.trycloudflare.com/auth/shopify/callback",
  "https://acc-skins-realty-highways.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
